language: objective-c
osx_image: xcode9.4

script:
  - xcodebuild -workspace Bohrium.xcworkspace -scheme Bohrium -configuration Debug -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8' clean build test
